[project]
name = "functions"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["core", "httpx", "strands-agents", "strands-agents-tools"]


[tool.uv.sources]
core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
