[tool.uv.workspace]
members = ["functions"]

[tool.uv]
dev-dependencies = [
    "ruff>=0.8.0",
    "mypy>=1.13.0", 
    "pytest>=8.2.0",
    "pytest-cov>=6.0.0",
    "pre-commit>=4.0.0",
]

# Tool Configuration
[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "E501",   # Line too long (handled by formatter)
    "D",      # pydocstring (optional for this project)
    "ANN",    # Type annotations (mypy handles this)
    "COM",    # Trailing commas (formatter handles this)
    "DJ",     # Django-specific
    "EM",     # Error message string literals
    "FBT",    # Boolean trap
    "TRY003", # Long messages in exceptions
    "S101",   # Use of assert (common in tests)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["PLR2004", "SLF001"]
"**/tests/**/*.py" = ["PLR2004", "SLF001"]

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["functions/tests"]
addopts = ["-v", "--tb=short", "--strict-markers"]
markers = ["unit: Unit tests", "integration: Integration tests"]
